contribution: Python Stub File
gorules/zen pull request #181
Opened 2024-06-19 17:36 UTC by iguessitsjeff

PR adds a stub file to the Python Binding source code in order to give a more clear description when implementing using the Python Package.

Implemented based on [Pyo3 Documentation](https://pyo3.rs/main/python-typing-hints)

### Vscode Before
![Before](https://github.com/gorules/zen/assets/62968348/e306ce5e-6b78-4a07-8094-012ad1a59c3c)

### Vscode After
![After](https://github.com/gorules/zen/assets/62968348/587dfdb6-59cd-42ea-9576-e23548bf446c)

2024-06-21 07:29 UTC, stefan-steadfast commented
This looks great, thanks for contributing. @iguessitsjeff is it enough to simply merge and Pyo3/Maturin will take care of the rest?

2024-06-21 08:45 UTC, stefan-gorules commented
This looks great, thanks for contributing. @iguessitsjeff is it enough to simply merge and Pyo3/Maturin will take care of the rest?

2024-06-21 08:49 UTC, stefan-gorules commented
This looks great, thanks for contributing. @iguessitsjeff is it enough to simply merge and Pyo3/Maturin will take care of the rest?

2024-06-21 13:12 UTC, iguessitsjeff commented
> This looks great, thanks for contributing. @iguessitsjeff is it enough to simply merge and Pyo3/Maturin will take care of the rest?

@stefan-gorules Yes, that is all taken care of by Pyo3/Maturin. One thing that I wanted to verify is the expected return values of some of the functions, for example the evaluate functions:
https://github.com/gorules/zen/blob/master/bindings/python/src/engine.rs#L101-L102

It looks like it can return different values other than a python dictionary. Can someone help to list all the expected return values and I can convert the return value into a Union type.

2024-07-04 10:00 UTC, stefan-gorules commented
Hi @iguessitsjeff, this has been held up slightly to make room for #185. After it's merged we can take a look at making minor changes to the stub (as we'll now provide async API for evaluation).

I'll try to provide types here in a bit in TypeScript format, as I'm not fully familiar with Python type capabilities. We can then take a look at updating Python types based on that.

2024-07-04 13:59 UTC, stefan-gorules requested changes
Please also see #185 which adds two new methods:

```python
ZenEngine.async_evaluate()
ZenDecision.async_evaluate()
```

Here we should return `Awaitable[EvaluateResponse]`

2024-07-04 13:59 UTC, stefan-gorules commented on bindings/python/zen.pyi
> +    def evaluate(self, key: str, ctx: dict, opts: Optional[dict] = None) -> dict: ...
Here in evaluate we return:

```
type EvaluateResponse = {
  performance: str;
  result: dict;
  trace: dict;
}
```

2024-07-04 13:59 UTC, stefan-gorules commented on bindings/python/zen.pyi
> +    def evaluate(self,ctx: dict, opts: Optional[dict] = None) -> dict: ...
Same as above (`EvaluateResponse`)

2024-07-04 13:59 UTC, stefan-gorules commented on bindings/python/zen.pyi
> +def evaluate_expression(expression: str, ctx: Optional[dict] = None) -> dict: ...
This returns `Any` as it can be a boolean, number etc.

2024-07-04 13:59 UTC, stefan-gorules commented on bindings/python/zen.pyi
> +def render_template(template: str, ctx: dict) -> dict: ...
This returns `Any` as well.

2024-07-09 00:14 UTC, iguessitsjeff commented on bindings/python/zen.pyi
> +def render_template(template: str, ctx: dict) -> dict: ...
Updated!

2024-07-09 00:25 UTC, iguessitsjeff commented
Apologies for the delay!
I made the updates based on the comments.

@stefan-gorules The layout of the struct helped, I created a [TypedDict](https://peps.python.org/pep-0589/) class as there is no structs in Python. The TypedDict allows users to access the object while also getting hints from the IDE as to what keys are present.

![TypedDict](https://github.com/gorules/zen/assets/62968348/1bfec812-2c89-4fa9-8a45-ec128d7463ac)

Additionally, added the Async Functions with the Awaitable return type. Validated that the type hints appear as expected when using `async.gather`.

![AsyncGather](https://github.com/gorules/zen/assets/62968348/60535be0-779d-4db3-aa5d-128875f324b0)

And you are able to access the same keys once accessing the index of the gathered results.

![AsyncTypedDict](https://github.com/gorules/zen/assets/62968348/aca46cb6-25f5-4f4b-b609-a5b7d36d78f2)

2024-07-09 09:42 UTC, stefan-gorules approved these changes

2024-07-09 12:10 UTC, merged