feat: add async support to python binding
gorules/zen pull request #185
Opened 2024-06-20 19:40 UTC by scottwthompson

I think there is a discrepancy with the NodeJS binding it can evaluate the customer_handler async but the python binding appears not to be able to do this.

I think some async support for the custom node handler in python would be a good add, so for example if you are making an API request in a custom node handler, not blocking the event loop during execution.

However async could be added by the zen team would be appreciated, this PR just to make the ask.

2024-06-21 07:31 UTC, stefan-steadfast commented
Hi @scottwthompson, thank you for the contribution.

Since I'm not actively in the Python world regarding naming etc. is it common pattern to have async_evaluate such as shown here? We'll also want to add the same to ZenDecision by the way.

2024-06-21 08:51 UTC, stefan-gorules commented
Hi @scottwthompson, would you be able to provide more details around the ergonomics of Python API. I haven't used async Python extensively, what's the most common way libs expose both async and sync? Is it common to do `async_*` prefix for method?

Also, would you be able to include implementation for `ZenDecision` as well? Otherwise looks good. Thanks for contribution.

2024-06-21 19:31 UTC, scottwthompson commented
@stefan-gorules Added for `ZenDecision`.

On the API question, I have no strong perspective on this but I would guess it's more common to see an entire async class or library separated out. Like `ZenAsyncEngine`. I.E:: https://www.python-httpx.org/async/.

But not that uncommon to have it just be a method: https://arq-docs.helpmanual.io/#arq.worker.Worker.async_run.

Keeping the bindings looking as similar as possible was my initial thoughts but happy to adjust if you prefer one over the other.

2024-06-28 11:08 UTC, stefan-gorules commented
Yep, I think method_async or async_method works well. Approved, waiting for pipelines and will merge.

2024-06-28 11:54 UTC, stefan-gorules requested changes

2024-06-28 11:54 UTC, stefan-gorules commented on bindings/python/src/custom_node.rs
> +        let result = future.expect("Future or result must be present")?.await?;
This should return an error instead of panicking (See `NodeResult`)

2024-07-04 09:56 UTC, stefan-gorules approved these changes

2024-07-04 10:10 UTC, merged